# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    gotenberg_url: '%env(GOTENBERG_URL)%'
    base_url: '%env(BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\GotenbergClient:
        arguments:
            $gotenbergUrl: '%env(GOTENBERG_URL)%'

    App\Controller\GeneratePdfController:
        arguments:
            $baseUrl: '%env(BASE_URL)%'
            $microservice_url: '%env(MICROSERVICE_URL)%'


    Doctrine\Persistence\ObjectManager: '@doctrine.orm.default_entity_manager'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
